models/Clients.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "clients".
 *
 * @property integer $id
 * @property string $name
 * @property string $surname
 * @property integer $gender
 * @property string $birth
 */
class Clients extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'clients';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'surname', 'gender', 'birth'], 'required'],
            [['gender'], 'integer'],
            [['birth'], 'safe'],
            [['name', 'surname'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'surname' => 'Surname',
            'gender' => 'Gender',
            'birth' => 'Birth',
        ];
    }

    /**
     * Get Client accounts
     * @return \yii\db\ActiveQuery
     */
    public function getAccounts(){
        return $this->hasMany(Accounts::className(), ['client_id'=>'id']);
    }

    /**
     * Using in dropdown List
     */
    public function getList(){

        $userList = ArrayHelper::map($this->find('id', 'CONCAT(name, surname) AS fullName')
            ->select(['id', new \yii\db\Expression("CONCAT( `surname`, ' ', `name`) as name")] )
            ->all(), 'id', 'name');

        return $userList;
    }

}

controllers/AccountsController.php
<?php

namespace app\controllers;

use app\models\Clients;
use Yii;
use app\models\Accounts;
use app\models\AccountsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AccountsController implements the CRUD actions for Accounts model.
 */
class AccountsController extends Controller
{
    /**
     * @inheritdoc
     */

    public function behaviors()
    {

        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index','create','update','view'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all Accounts models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AccountsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $modelClient = new Clients();
        $clientsList = $modelClient->getList();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'clientsList'=>$clientsList
        ]);
    }

    /**
     * Displays a single Accounts model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Accounts model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Accounts();

        if ($model->load(Yii::$app->request->post()) ) {

            if($model->validate()){

                $model->amount = $model->deposit;
                if($model->date) $model->date = date('Y-m-d H:i:s', strtotime($model->date));
                    else $model->date = date('Y-m-d H:i:s');

                if($model->save()){
                    Yii::$app->session->setFlash('success', 'Account successfully created');
                    return $this->redirect(['view', 'id' => $model->id]);
                    //return $this->refresh();// перезагрузка и очистка формы
                }else{
                    Yii::$app->session->setFlash('error', 'Error saving new account: '.$model->getErrors());
                }

            }else{
                Yii::$app->session->setFlash('danger', 'Error data validation');
            }

        } else {

            $modelClient = new Clients();
            $clientsList = $modelClient->getList();

            return $this->render('create', [
                'model' => $model, 'clientsList'=>$clientsList
            ]);
        }
    }

    /**
     * Updates an existing Accounts model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        Yii::$app->session->setFlash('danger', 'Editing is forbidden.');
        //if ($model->load(Yii::$app->request->post())) {
            //if($model->save()) return $this->redirect(['view', 'id' => $model->id]);
        //}

            $modelClient = new Clients();
            $clientsList = $modelClient->getList();

            return $this->render('update', [
                'model' => $model, 'clientsList'=>$clientsList
            ]);
    }

    /**
     * Deletes an existing Accounts model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        Yii::$app->session->setFlash('danger', 'Deleting is forbidden.');

        //$this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Accounts model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Accounts the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Accounts::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/ClientsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Clients;
use app\models\ClientsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientsController implements the CRUD actions for Clients model.
 */
class ClientsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index','create','update','view'],
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all Clients models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Clients model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Clients model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Clients();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->birth = date('Y-m-d 00:00:00', strtotime($model->birth));
            if($model->save()){
                Yii::$app->session->setFlash('success', 'Client successfully added');
                return $this->redirect(['view', 'id' => $model->id]);
            }else{
                Yii::$app->session->setFlash('error', 'Error adding new client: '.$model->getErrors());
            }

        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Clients model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->birth = date('Y-m-d 00:00:00', strtotime($model->birth));
            if($model->save()){
                Yii::$app->session->setFlash('success', 'Client data successfully saved');
                return $this->redirect(['view', 'id' => $model->id]);
            }else{
                Yii::$app->session->setFlash('error', 'Error saving client data: '.$model->getErrors());
            }

        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Clients model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {

        //$this->findModel($id)->accounts->delete();

        //dump($this->findModel($id)->accounts);
        foreach($this->findModel($id)->accounts as $account){
            $account->delete();
        }
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Clients model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Clients the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Clients::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/clients/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Clients */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="clients-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <? echo $form->field($model, 'gender')->dropDownList(['1' => 'Male', '2' => 'Female'],['prompt'=>'Select gender']); ?>

    <?

    if($model->birth) {
        $birthStr = date('d-M-Y', strtotime($model->birth));
        $model->birth = $birthStr;
    }

    echo $form->field($model, 'birth')->label('Birthday Date')->widget(
        'kartik\date\DatePicker',
        [
            'name' => 'Clients[birth]',
            'type' => DatePicker::TYPE_COMPONENT_APPEND,
            'options' => ['placeholder' => 'Select birthday date ...' ],//'readonly'=>'readonly'
            'pluginOptions' => [
                'format' => 'dd-M-yyyy',
                'autoclose'=>true,
                'yearRange' => '1930:2030',
                'changeYear' => true,
                'todayHighlight' => true
            ]
        ]
    );
    ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/clients/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\ClientsSearch */
/* @var $form yii\widgets\ActiveForm */
?>



<div class="clients-search">


    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]);

    ?>
    <?= $form->field($model, 'id') ?>
    <?= $form->field($model, 'name') ?>
    <?= $form->field($model, 'surname') ?>

    <?php echo $form->field($model, 'gender')->dropDownList(['1' => 'Male', '2' => 'Female'],['prompt'=>'Select gender']); ?>



    <?php
    /*
    if($model->birth) $birthStamp = strtotime($model->birth);
        else $birthStamp = time();
    echo '<label>Birthday Date</label>';
    echo DatePicker::widget([
        'name' => 'ClientsSearch[birth]',
        'type' => DatePicker::TYPE_COMPONENT_APPEND,
        'value' => date('d-M-Y', $birthStamp),
        'options' => ['placeholder' => 'Select birthday date ...', 'readonly'=>'readonly'],
        'pluginOptions' => [
            'format' => 'dd-M-yyyy',
            'autoclose'=>true,
            'yearRange' => '1930:2030',
            'changeYear' => true,
            'todayHighlight' => true
        ]
    ]);
    echo '<br>';
    */
    ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/clients/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Clients */

$this->title = 'Add New Client';
$this->params['breadcrumbs'][] = ['label' => 'Bank Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="clients-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/clients/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\components\helpers\DataFormatHelper;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ClientsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Bank Clients';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="clients-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <hr>
    <p>
        <?= Html::a('Add New Client', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <hr>


    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => [

                        'id',
                        'name',
                        'surname',
                        [
                            'attribute' => 'gender',
                            'value' => function($model, $key, $index, $widget) {
                                return DataFormatHelper::getDisplayGender($model->gender);
                            },
                        ],
                        [
                            'attribute' => 'birth',
                            'value' => function($model, $key, $index, $widget) {
                                return DataFormatHelper::getDisplayDate($model->birth, 'date');
                            }
                        ],

                        [
                            'class' => \yii\grid\ActionColumn::className(),
                            'buttons'=>[
                                'accounts'=>function ($url, $model) {
                                    $customurl=Yii::$app->getUrlManager()->createUrl(['accounts/index','AccountsSearch[client_id]'=>$model['id']]); //$model->id для AR
                                    return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-list"></span>', $customurl,
                                        ['title' => Yii::t('yii', 'Accounts'), 'data-pjax' => '0']);
                                }
                            ],
                            'template'=>'{accounts}',
                            'header' => 'Accounts'
                        ],

                        [
                            'class' => \yii\grid\ActionColumn::className(),
                            'template'=>' {view}  {update}  {delete}',
                        ]

                    ],
                ]); ?>
            </div>
            <div class="col-md-3">
                <h4>Filter clients:</h4><hr>
                <?php  echo $this->render('_search', ['model' => $searchModel]); ?>
            </div>

        </div>

    </div>

</div>

views/clients/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Clients */

$this->title = 'Edit Client: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Bank Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="clients-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/clients/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

use app\components\helpers\DataFormatHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Clients */

$this->title = $model->surname.' '.$model->name;
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="clients-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            [
                'attribute' => 'id',
                'value' => '#'.$model->id,
                'label' => 'Client ID',
            ],
            'name',
            'surname',
            [
                'attribute' => 'gender',
                'value' => DataFormatHelper::getDisplayGender($model->gender),
            ],
            [
                'attribute' => 'birth',
                'value' => DataFormatHelper::getDisplayDate($model->birth, 'date'),
                'label' => 'Birthday date',
            ],
        ],
    ]) ?>

</div>